### ISSUE TITLE
elephant.signal_processing.butter doesn't work with neo 0.8.0.dev0

### ISSUE THREAD

**Issue by kkorvasova** [NeuralEnsemble/elephant#195]
When calling elephant.signal_processing.butter with neo 0.8.0.dev0, I am getting the error
"AttributeError: 'AnalogSignal' object has no attribute 'duplicate_with_new_array' "
With neo 0.6.1 it worked. 

An example that reproduces the error:

```python
import elephant
import neo
import numpy as np
import quantities as qt

sampling_rate = 1000.*qt.Hz
t_stop = 100. * qt.s
t_start = 0. * qt.s
potential = neo.core.AnalogSignal(
signal=np.random.rand(int(t_stop.magnitude)),
units=1 * qt.mV,
sampling_rate=sampling_rate,
t_start=t_start,
name='test',
times=np.arange(t_start, t_stop, 1./sampling_rate))

filt_potential = elephant.signal_processing.butter(
potential,
highpass_freq=30.,
lowpass_freq=60.)
```

**Comment by jpgill86** [comment]
This will be fixed with #189.

**Comment by jpgill86** [comment]
This should no longer be a problem with Neo 0.7.1, released today. See [this post](https://github.com/NeuralEnsemble/elephant/pull/189#issuecomment-446987346). I think this issue can be closed.

**Comment by dizcza** [comment]
Confirmed with neo v0.7.1. The issue is fixed.
